ports:
  - port: 8000
    onOpen: open-preview
tasks:
  - init: yarn install && yarn build
    command: yarn start
vscode:
  extensions:
    - jpoissonnier.vscode-styled-components@0.0.28:Qde/ISuGvFTPjoaMf1FmnQ==
    - paulmolluzzo.convert-css-in-js@1.1.3:YnjK47pXScU3DMFfQzkkOw==
